## Numpy Exercise

#### Q1. Import NumPy as np

In [1]:
import numpy as np

#### Q2. Create an array of 10 zeros

In [2]:
my_list=[0,0,0,0,0,0,0,0,0,0]

In [3]:
np.array(my_list)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Q3. Create an array of 10 ones

In [6]:
my_list2=[1,1,1,1,1,1,1,1,1,1]

In [7]:
np.array(my_list2)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#####  Q4. Create an array of 10 fives

In [10]:
my_list3=[5,5,5,5,5,5,5,5,5,5]

In [11]:
np.array(my_list3)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
np.ones(10)*5,int

(array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]), int)

##### Q.5 Create an array of the integers from 10 to 50

In [14]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

##### Q.6 Create an array of all the even integers from 10 to 50

In [15]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Q.7 Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q.8 Create a 3x3 identity matrix

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Q.9 Use NumPy to generate a random number between 0 and 1

In [19]:
np.random.rand()


0.4156916358710243

#### Q.10 Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution


In [20]:
np.random.randn(25)


array([ 1.33706801,  1.19507879, -0.29120104, -0.52824734, -1.63427246,
        1.11350372, -0.17875531, -0.45336121, -0.13848777, -0.38910028,
        0.93597033, -1.0685857 ,  1.16264976, -1.11783414,  0.25809555,
       -1.7317223 ,  0.21789717, -0.18555495, -1.50122687,  0.81798174,
        1.71895848,  1.35177816, -0.43346295,  0.25622116, -1.60060923])

#### Q.11 Create the following matrix:

In [21]:
np.linspace(0.01,1,100) .... # 1D


array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [22]:
np.linspace(0.01,1,100).reshape(10,10) .... # 2D

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Q.12 Create an array of 20 linearly spaced points between 0 and 1:

In [23]:
np.linspace(0,1,20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Q.13 Numpy Indexing and Selection

#### Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs :

In [24]:
arr=np.arange(1,26).reshape(5,5)

In [25]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [28]:
# How to pitch 20

In [27]:
arr[3,4]

20

In [28]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [29]:
arr[4,0:]

array([21, 22, 23, 24, 25])

In [30]:
arr[4,0:5]

array([21, 22, 23, 24, 25])

In [31]:
arr[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
arr[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Q.14 Now do the following
###     i) Get the sum of all the values in mat

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
arr.sum()

325

In [35]:
np.sum(arr)

325

#### ii) Get the standard deviation of the values in mat

In [36]:
arr.std()

7.211102550927978

#### iii) Get the sum of all the columns in mat

In [41]:
arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [42]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [43]:
arr.sum(axis=0) ...# Row axis is zero

array([55, 60, 65, 70, 75])